//@version=3
study("Golden Volume | Kooshini", overlay=false)
// inputs
malen = input(20, type = integer, title = 'Moving average length')
ltfmalen = input(20, type = integer, title = 'Long Term Moving average length')
show = input(true, title = 'Show moving average?')
peak_multiplier = input(2, type = float, title = 'Peak Multiplier')
ltf_multiplier = input(0.3, type = float, title = 'Low Vol Multiplier')

// calcs
ma = ema(volume,malen)
ltfma = ema(volume,ltfmalen)
peaks = ma + ma * peak_multiplier

lowvolume = volume < ltfma * ltf_multiplier
highvolume = volume > peaks

clr = if (volume > peaks)
    clr = yellow
else
    clr = close > open ? #53B987:#EB4D5C

// plots    
plot(volume, color = clr, style = columns, title = 'Volume')
plot(show? ma:na, title = 'Moving average', color=white, style=area, transp=70)
bgcolor(color=lowvolume ? #5782C1 : na, transp=70)
plotchar(lowvolume, char='▾', size=size.small, location=location.bottom, color=#1E88E5)

// Alerts
alertcondition(condition=highvolume,
     title="High Volume Alert",
     message="Volume is higher than the EMA of the last X bars")
alertcondition(condition=lowvolume,
     title="Low Volume Alert",
     message="Volume is x% percent lower than the X EMA, potential move imminent")
